services:
  accounts-db:
    container_name: accounts-db
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: accounts-db
    extends:
      file: common-config.yml
      service: microservice-db-config

  loans-db:
    container_name: loans-db
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: loans-db
    extends:
      file: common-config.yml
      service: microservice-db-config

  cards-db:
    container_name: cards-db
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: cards-db
    extends:
      file: common-config.yml
      service: microservice-db-config

  configserver:
    image: "ganeshshet/configserver:v2"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "ganeshshet/accounts:v2"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accounts-db:3306/accounts-db"
    depends_on:
      accounts-db:
        condition: service_healthy
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: "ganeshshet/loans:v2"
    container_name: loans-ms
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loans-db:3306/loans-db"
    depends_on:
      loans-db:
        condition: service_healthy
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: "ganeshshet/cards:v2"
    container_name: cards-ms
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cards-db:3306/cards-db"
    depends_on:
      cards-db:
        condition: service_healthy
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  springbank:
    driver: "bridge"